# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TeamMood - Track The Well-Being of Your Team
email: hello@teammood.com
description: > # this means to ignore newlines until "baseurl:"
  Track the well-being of your team, easily.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.teammood.com" # the base hostname & protocol for your site
twitter_username: teammood

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap